language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: sonarqubegeekshubs
    branches:
    - ".*"
    token:
      secure: aVAZAcJ14KGvxeEvUsSma8Rz+f20fWqsJ4xcscH8ZcWlwqyoiL4C0smrC/5IGiWs5a+YaDVfheADGYuVRrcMqWFKhnZDryXS5Q0ErGbm+9HYWQv9fg9pJwkOItOkRlajNh2NV8NBT7ccsVYm9EI5eqzYPpsEthGrXMYbuMv+XosF0fLgpRoZKn56hLiP5oTqx0tbbQY6H7k8Q5+tjFW/Ml6jMV+w4uo4JPx7T7NTfIZ9nxeegnKg7wyKJ1e/+MZKcLPRq1ASDsNIOOotfvqz64LRGuDu/MTmpbX6akMsmn755xruninPiTq05117q7d7M5wv5jQTGSzb/SqPVHatwjLN65ySk1KTWP9nK8Mm3bMQlnVQSNpkmV9wSqbg3xQN/p78Tj20nwd+8Z19CKc/LZQzVbBtMhNWphan8o9Cj4PrGGu2y2EuI8iZH/Eqjz34C75duOjKEY6hOdY+4Gil9Pnx+oWXzCpsjiVBWlPguqj4NdCE72D8r1tFeOjGyhbd7IicriC3UB/hLEV/XSOTffJszIUN4DRRH/F8/lwIYshubjvgN2fb0INQjrYdJATc63z3k7ZvXmnHmfkKybkGm2gvyXduh5dpwXjYwyjiSc0X0T/TIp13r4EKKS32rnUIYhLIabP0fszN0+o4JGNhplViegn9h8Ijb1OUVsJ1LAc=
    github_token:
      secure: iAy4HF/pqMRLrPROGBAHYhRKwIzer7XAloz/JqkaZN0/gWX2JQ7juMzx0PFlbmswDlZBscsuc+2+suhli44Cng3xB22QxfDB3VSC+bsiVPA9Y24U5OYvH/i6Zr02TpYHEjppb1N52Rm8RJgJyf482mUkUoo7gyfXiPw5PqskoxihRddXXKzFdmAVYFJOUzfDm9J0Er/Suf/U0NYyC5IJfaSP6wgyYyRVqZZvUW8dcTD0Vd6u20QGJbXTBzzdeHfvCxf6uIByi4q+YPtiG/jld+pKPjxMgN4Kd4tYT0IDx5/O7qkAXmlCmamKj3boaLPvck7F/0O2EhrzTgbPPVRg+KWIlSfZgrXZz/ueqtYLiV7CGYIXtxOw9y3B1/DptdTvlR9wtDx583dU6D5DqCWjeMjobkgeX0yPXU0ooOzkAa6disGa61KJ4dlKFyeqTNiBLN17lvcP664bI79P/DE90MbhYShxIf2ccJD8evdoAjCr6IW8APDmobD4iSCD+mQRpY7oqvEXghgYGN5y87fnlECSOccj0aUSwPqlN4Xt3iAZQELOVd8k7ZOaLn81cGjL0ggaQAQFgIghVXbyc60hijds6/DjMtBR3qQBac09+l5IBTsJ22AGnpf7AFSdIJF89ZLzB5vPhpj1HAscNnhn+DmRv4AsMCVVPoa8R+wbu/s=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
