language: java

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: sonarqubegeekshubs

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

notifications:
  email: false
