language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: sonarqubegeekshubs
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
